version: '2.0'
services:
  apiteste:
    image: apitest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - api_db
  api_db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: jkal123skjdjka6u7d37sdioqwdlaksd*
    volumes:
      -  ./data:/var/lib/mysql:rw
    ports:
      - "3306:3306"